config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

app_name = "core"
urlpatterns = [
    #path("", views.all_rooms, name="home")
    path("", views.HomeView.as_view(), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    #path("<int:pk>", views.room_detail, name="detail")
    path("<int:pk>", views.RoomDetail.as_view(), name="detail")
]

core/models.py
from django.db import models

class TimeStampedModel(models.Model):

    """ Time Stamped Model """

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render
from django.views.generic import ListView
from datetime import datetime
from rooms import models as room_models
# Create your views here.


def all_rooms(request):
    rooms = room_models.Room.objects.all()
    return render(request, "core/room_list.html", context={
        "rooms": rooms
    })

class HomeView(ListView):
    model = room_models.Room
    template_name = "core/room_list.html"
    paginate_by = 10
    paginate_orphans = 5
    page_kwarg = "page"
    ordering = "created_at"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = datetime.now()
        return context

core/templates/core/room_list.html
{% extends "base.html" %}

{% block page_title %}home{% endblock page_title %}

{% block content %}

{{now}}
{% for room in object_list %}
<h4>
    <a href="{% url "rooms:detail" room.pk %}">{{ room.name }} / ${{ room.price }}</a>
</h4>

{% endfor %}
<h5>
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages}} 
    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
</h5>
{% endblock content%}